### PR TITLE
Bump jetbrains annotation to 20.1.0.

### PR DESCRIPTION
**Pull request by benwoo1110**

### CODE REVIEW

**Comment by nicegamer7** [comment]
I tried this locally (and also bumped up the intrumentor) and it wouldn't build. Can you try that on your end and tell me if you get the same thing?

**Comment by benwoo1110** [comment]
With java 8 its fine, but I didn't test with java 11 this this PR was made before that issue was reported.

**Comment by nicegamer7** [comment]
I was testing on Java 15. I'll try with 8.

**Comment by nicegamer7** [comment]
It still doesn't build with the updated instrumentor. I guess we can leave this until 5.0.0 unless it fixes #2559.

**Comment by benwoo1110** [comment]
Yep this is something for 5.0.0, just made a PR to solve that issue. #2573

**Pull request closed without merging**
