### PR TITLE
Sorts worldname by alphabetical order

### LINKED ISSUE #1960: Feature request: Order mv list output alphabetically
Spigot 1.13.2
MV-Core 2.7.0-SNAPSHOT-b747

```
>mv list
[22:58:17 INFO]: ====[ Multiverse World List ]====
[22:58:17 INFO]: minigames - NORMAL
[22:58:17 INFO]: yellowdog - NORMAL
[22:58:17 INFO]: skyblock-the-end - THE_END
[22:58:17 INFO]: void - NORMAL
[22:58:17 INFO]: skyblock-nether - NETHER
[22:58:17 INFO]: luckyblock - NORMAL
[22:58:17 INFO]: parkour - NORMAL
[22:58:17 INFO]: skyblock - NORMAL
[22:58:17 INFO]: playground-the-end - THE_END
[22:58:17 INFO]: playground - NORMAL
[22:58:17 INFO]: playground-nether - NETHER
[22:58:17 INFO]: yellowdog-nether - NETHER
[22:58:17 INFO]: lobby - NORMAL
[22:58:17 INFO]: city - NORMAL
[22:58:17 INFO]: city-nether - NETHER
```
would be more user-friendly if it were
```
>mv list
[22:58:17 INFO]: ====[ Multiverse World List ]====
[22:58:17 INFO]: city - NORMAL
[22:58:17 INFO]: city-nether - NETHER
[22:58:17 INFO]: lobby - NORMAL
[22:58:17 INFO]: luckyblock - NORMAL
[22:58:17 INFO]: minigames - NORMAL 
[22:58:17 INFO]: parkour - NORMAL
[22:58:17 INFO]: playground - NORMAL
[22:58:17 INFO]: playground-nether - NETHER
[22:58:17 INFO]: playground-the-end - THE_END
[22:58:17 INFO]: skyblock - NORMAL
[22:58:17 INFO]: skyblock-nether - NETHER
[22:58:17 INFO]: skyblock-the-end - THE_END
[22:58:17 INFO]: void - NORMAL
[22:58:17 INFO]: yellowdog - NORMAL
[22:58:17 INFO]: yellowdog-nether - NETHER
```

### PR DESCRIPTION
**Pull request by benwoo1110**
Make MVWorld implement Comparable interface.

Had to add new WorldManager#getSortedMVWorlds as return type is different.

fixes #1960

### CODE REVIEW

**Comment by benwoo1110** [comment]
image
Alphabetical order!

**Review by nicegamer7 — APPROVED** [review]
LGTM 👍.

**Comment by benwoo1110** [comment]
I think this one let use command display, cant rmb what I coded 9 month ago anyways

**Comment by SlimeDog** [comment]
Is this going to be added to MV 4.x ?

**Pull request closed without merging**
