### PR TITLE
Update to 1.15.2

### PR DESCRIPTION
**Pull request by jason-s-yu**
Update dependencies to use 1.15.2, including updating the spigot dependency and Vault dependency.

### CODE REVIEW

**Comment by willies952002** [comment]
Simply updating the dependencies to a newer version isn't enough in the case of a 1.15.2 update.

Since `org.bukkit.TravelAgent` was removed recently, `c.o.M.l.MVPlayerListener` and `c.o.M.u.BukkitTravelAgent` fail to compile. These issues would need to be resolved before a release with full 1.15.2 support is possible.

**Comment by filips123** [comment]
> These issues would need to be resolved before a release with full 1.15.2 support is possible.

What does this mean? Does Multiverse already partly works with Minecraft 1.15.2 (maybe with some missing features) or is it completely impossible to use it with 1.15.2?

**Comment by dumptruckman** [comment]
@filips123 It does work with 1.15.2.
@jason-s-yu I'd rather not switch to spigot-api because we do not need any of the additional features it adds.

**Comment by nicegamer7** [comment]
I'm going to close this in favour of #2414.

**Pull request closed without merging**
