### PR TITLE
Queue system cleanup

### PR DESCRIPTION
**Pull request by benwoo1110**
Just some small cleanup and docs update to the new QueueCommandSystem.

### CODE REVIEW

**Comment by nicegamer7** [comment]
I think the DummyCommandBlockSender should return `true` for `isOp()`.

Just going off Spigot's [CraftBlockCommandSender](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/command/CraftBlockCommandSender.java).

**Comment by benwoo1110** [comment]
Not really, bcu our `DummyCommandBlockSender` should not be used for any form of permission checks

**Comment by nicegamer7** [comment]
Doesn't a command block technically have all permissions?

**Comment by benwoo1110** [comment]
`DummyCommandBlockSender` is just use as a dummy reference for our mapping, the actually queue command execution uses the actual `CraftBlockCommandSender` and has nothing to do with our `DummyCommandBlockSender`

**Comment by nicegamer7** [comment]
Ah okay, I see what you mean. Sounds good.

**Comment by nicegamer7** [comment]
Just a couple typos in the first Javadoc, I'll fix them and merge.

**Comment by benwoo1110** [comment]
alright sure!

**Review by nicegamer7 — APPROVED** [review]

**Pull request merged**
