### PR TITLE
Use the World Attribute from the Location Class

### PR DESCRIPTION
**Pull request by nicegamer7**
While trying to figure out the problem behind #2332 (it ended up being a Spigot bug), I realized that MV's SpawnLocation Class uses it's own World attribute and ignores the one present in the Location Class.

I couldn't understand why this was done, especially since MVWorld.getSpawnLocation() would return with a location with a null World. This PR removes SpawnLocation's World attribute in favour of World's.

### CODE REVIEW

**Comment by nicegamer7** [comment]
I'm marking this as a draft until further notice... maybe indefinitely.

**Comment by benwoo1110** [comment]
Is this.. still needed?

**Comment by nicegamer7** [comment]
It was never needed, it's just something I realized that confused me. The reason I set this PR as a draft is because dump and I didn't know why this was done in the first place, so we weren't sure if this change would break anything. I think this change *might* reduce memory usage by a tiny bit.

**Comment by benwoo1110** [comment]
I believe weak reference is used bcu world properties are kept in memory even if the world is unloaded.

I just updated to `toString` method so debug output doesnt keep showing null world https://github.com/Multiverse/Multiverse-Core/commit/3fc3663d5d2839f2b48df478176244e204165556

**Pull request closed without merging**
