### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by Rigby90**
Pull request for CircleCI to build and test :(

### CODE REVIEW

**Comment by dumptruckman** [comment]
Problem appears to be getting craftbukkit, not vault.

**Comment by Rigby90** [comment]
Indeed, back at home now so was going to take a proper look.

**Comment by Rigby90** [comment]
@dumptruckman Ok, looks like it struggles to get CraftBukkit because of your Logging library.

https://github.com/dumptruckman/Logging/blob/master/pom.xml

I'm able to add the Essentials repo to grab the version required for building. Any reason why that relies on CraftBukkit and not Bukkit? Only saw a reference to the Plugin class.

**Comment by dumptruckman** [comment]
Huh. I forgot that was a separate lib. Anyway, I updated it to use Bukkit instead. Build successful on our ci.

**Comment by Rigby90** [comment]
Nice, unable to get the tests to pass on my PC. Not sure why, been too long!

**Comment by TWSSYesterday** [comment]
Fixed in #1586 ?

**Pull request closed without merging**
