### PR TITLE
Improve worldname checks

### PR DESCRIPTION
**Pull request by benwoo1110**
Adds config option to allow unsafe (e.g. / ) to be part of the world name. Those that know what they doing can use it for subdir worlds etc. Also, integrate the new world name restrictions from #2353 to WorldNameChecker to make things cleaner.

### CODE REVIEW

**Comment by benwoo1110** [comment]
example output:
image

Test build:
[Multiverse-Core-4.2.3-SNAPSHOT.zip](https://github.com/Multiverse/Multiverse-Core/files/6489321/Multiverse-Core-4.2.3-SNAPSHOT.zip)

**Comment by nicegamer7** [comment]
I don't like the idea of allowing unsafe world names. I liked your idea where we check if the world is in the world container. Would that not work?

**Comment by benwoo1110** [comment]
It will work, just more work haha, but yea its possible. I can try to see if it works out in code.

**Comment by nicegamer7** [comment]
Okay, sounds good.

**Comment by nicegamer7** [comment]
Actually, I think I have a simple solution. A world name must not start with a `/` and must not contain `..`.

Pretty sure that will ensure worlds stay within the server's directory.

**Pull request closed without merging**
